image: docker:stable
variables:
  KUBECTL: v1.17.0
services:
  - docker:dind
stages:
  - test
test:
  stage: test
  script:
    - apk add -U wget
    - wget -O ./minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    - chmod +x ./minikube
    - wget -O ./kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - ./minikube start --force
    - ./kubectl get nodes -o wide
    - ./kubectl get pods --all-namespaces -o wide
    - ./kubectl get services --all-namespaces -o wide