image: docker:stable
variables:
  KUBECTL: v1.17.0
services:
  - docker:dind
stages:
  - test
test:
  stage: test
  script:
    - apk add -U wget
    - wget -O /usr/local/bin/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64
    - chmod +x /usr/local/bin/minikube
    - wget -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x /usr/local/bin/kubectl
    - minikube start --force
    - kubectl get nodes -o wide
    - kubectl get pods --all-namespaces -o wide
    - kubectl get services --all-namespaces -o wide